services: 
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
      
      #joga o dump, inicialmente, dentro do volume.
      - ./dumps:/docker-entrypoint-initdb.d 
      
    ports:
      - "3307:3306"

    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --pasword="root" --silent']
      interval: 3s
      retries: 5
      start_period: 30s

volumes:
  db_data: